### PR TITLE
Added int conversion for timespan because time

### PR DESCRIPTION
**Pull request by ppajersk**
delta was throwing an error trying to process a string value for time

### CODE REVIEW

**Comment by ppajersk** [comment]
This double commit was intentional, this project is pretty much nearing its final form minus bug patches, simpler to bundle both of these changes together.

**Comment by jlothian** [comment]
Commenting.

**Review by jlothian — COMMENTED** [review]
review comment

**Comment by ppajersk** [comment]
Closing, not needed anymore

**Pull request closed without merging**
